Dev/ignition 8.1 1.2
hms-networks/IgnitionEwonConnector pull request #108
Opened 2021-01-21 20:19 UTC by alexjhawk

2021-01-21 20:23 UTC, alexjhawk commented
There will be 1 more (small) pull request to follow this one.

2021-01-21 21:13 UTC, oliver-walker-hms requested changes

2021-01-21 21:13 UTC, oliver-walker-hms commented on readme.md
> +To learn more about Talk2M tokens and how to generate them, please refer to Section 4.6 of the DMWeb API reference guide, found at https://developer.ewon.biz/system/files_force/rg-0005-00-en-referenc
Extra comma included.
```Suggestion
To learn more about Talk2M tokens and how to generate them, please refer to Section 4.6 of the DMWeb API reference guide found at: [DMWeb API Reference Guide](https://developer.ewon.biz/system/files_force/rg-0005-00-en-reference-guide-for-dmweb-api.pdf?download=1)
```

2021-01-21 21:22 UTC, alexjhawk commented on readme.md
> +To learn more about Talk2M tokens and how to generate them, please refer to Section 4.6 of the DMWeb API reference guide, found at https://developer.ewon.biz/system/files_force/rg-0005-00-en-referenc
fixed

2021-01-21 22:04 UTC, TomKimsey requested changes

2021-01-21 22:04 UTC, TomKimsey commented on readme.md
> +To learn more about Talk2M tokens and how to generate them, please refer to Section 4.6 of the DMWeb API reference guide found at: [DMWeb API Reference Guide](https://developer.ewon.biz/system/files_
```suggestion
To learn more about Talk2M tokens and how to generate them, please refer to Section 4.6 of the DMWeb API reference guide found at: [DMWeb API Reference Guide](https://developer.ewon.biz/system/files_force/rg-0005-00-en-reference-guide-for-dmweb-api.pdf).
```

2021-01-21 22:04 UTC, TomKimsey commented
Just one minor thing

2021-01-21 22:08 UTC, alexjhawk commented on readme.md
> +To learn more about Talk2M tokens and how to generate them, please refer to Section 4.6 of the DMWeb API reference guide found at: [DMWeb API Reference Guide](https://developer.ewon.biz/system/files_
changed

2021-01-22 13:54 UTC, TomKimsey approved these changes

2021-01-22 13:58 UTC, oliver-walker-hms approved these changes

2021-01-22 13:58 UTC, merged