Dev/154 155
hms-networks/IgnitionEwonConnector pull request #156
Opened 2024-09-30 18:36 UTC by it-hms

closes #154 
closes #155

2024-09-30 18:49 UTC, it-hms commented
@alexjhawk, These changes still need to be tested

2024-09-30 19:14 UTC, alexjhawk requested changes
It looks good, aside from the two recommendations. We can talk about testing tomorrow.

2024-09-30 19:14 UTC, alexjhawk commented on eWonConnector-gateway/src/main/java/com/hms_networks/americas/sc/ignition/comm/requests/m2w/M2WebEwonUpdateTagValuesRequest.java
> +  public static String TagValToString(Object obj) {
```suggestion
  public static String tagValToString(Object obj) {
```

2024-09-30 19:14 UTC, alexjhawk commented on eWonConnector-gateway/src/main/java/com/hms_networks/americas/sc/ignition/comm/requests/m2w/M2WebEwonUpdateTagValuesRequest.java
> +          .append(TagValToString(tagNameValuePair.getValue()));
```suggestion
          .append(tagValToString(tagNameValuePair.getValue()));
```

2024-10-08 17:05 UTC, benlbaum commented
@it-hms @alexjhawk are we able to get v2.0.1 merged so that we can test the Issue #154 fix?

2024-10-08 17:39 UTC, it-hms commented
@alexjhawk ,
The changes you requested are completed. Could you please add a review?

2024-10-08 17:46 UTC, alexjhawk approved these changes

2024-10-08 19:41 UTC, merged